# Generated by Django 3.0.3 on 2020-04-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='email',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='manager',
            name='utxt',
            field=models.TextField(default=''),
        ),
    ]
